[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
material-yew = { version = "0.3.0", features = ["full"] }
# client side rendering
yew = { version = "0.20.0", features = ["csr"] }

# gloo-net = "0.6.0"
gloo = { version = "*" }
log = "0.4.22"
yew-router = "0.17.0"
