[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.7", features = ["macros"] }
rmodbus = "0.9.9"
serialport = { version = "4.5.1", features = ["serde"] }
tokio = { version = "1.40.0", features = ["full"] }


log = "0.4.22"
env_logger = "0.11.5"
